trigger:
  - master

pr:
  - master
  - staging
  - prod

variables:
  solution: 'CrossNews.sln'
  buildConfiguration: 'Release'
  nugetVersion: 4.5

jobs:
- job: Core
  displayName: Core

  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - task: NugetToolInstaller@0
    displayName: 'Use NuGet $(nugetVersion)'
    inputs:
      versionSpec: '$(nugetVersion)'

  - task: NugetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    displayName: 'Run tests'
    inputs:
      testAssemblyVer2: |  
       **\*tests*.dll
       !**\*TestAdapter.dll
       !**\obj\**

      codeCoverageEnabled: true
      otherConsoleOptions: /InIsolation
      configuration: '$(buildConfiguration)'
